
services:
  auth-service:
    image: auth-service
    build: ./auth-service/
    restart: always
    ports:
      - 8001:8000
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_URL: "postgres://user:password@postgres:5432/authdb?sslmode=disable&connect_timeout=5"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0
    restart: always
    ports:
      - 5432:5432
    deploy:
      mode: replicate
      replicas: 1
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    command: |
      bash -c "
        docker-entrypoint.sh postgres & 
        until pg_isready -U user; do
          echo 'Waiting for Postgres to be ready...'
          sleep 2
        done &&
        psql -U user -tc \"SELECT 1 FROM pg_database WHERE datname = 'authdb';\" | grep -q 1 || psql -U user -c 'CREATE DATABASE authdb;' &&
        psql -U user -tc \"SELECT 1 FROM pg_database WHERE datname = 'productdb';\" | grep -q 1 || psql -U user -c  'CREATE DATABASE productdb;' && 
        psql -U user -tc \"SELECT 1 FROM pg_database WHERE datname = 'orderdb';\" | grep -q 1 || psql -U user -c 'CREATE DATABASE orderdb;' && 
        tail -f /dev/null
      "

