
services:
  gateway:
    image: gateway
    build: ./gateway/
    restart: always
    ports:
      - 8080:8080 ## host(localhost):container(inside docker)
    depends_on:
      - auth-service
      - product-service
    environment:
      PORT: "8080"

  auth-service:
    image: auth-service
    build: ./auth-service/
    restart: always
    ports:
      - 8081:8080
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: "8081"
      DSN: "postgres://user:password@postgres:5432/authdb?sslmode=disable&connect_timeout=5"
    depends_on:
      - postgres

  product-service:
    image: product-service
    build: ./product-service/
    restart: always
    ports:
      - 8082:8080
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: "8082"
      DSN: "postgres://user:password@postgres:5432/productdb?sslmode=disable&connect_timeout=5"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0
    restart: always
    ports:
      - 5432:5432
    deploy:
      mode: replicate
      replicas: 1
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ./db/init-auth.sql:/docker-entrypoint-initdb.d/init-auth.sql 
      - ./db/init-product.sql:/docker-entrypoint-initdb.d/init-product.sql
    command: |
      bash -c "
        docker-entrypoint.sh postgres & 
        until pg_isready -U user; do
          echo 'Waiting for Postgres to be ready...'
          sleep 2
        done &&
        psql -U user -tc \"SELECT 1 FROM pg_database WHERE datname = 'authdb';\" | grep -q 1 || psql -U user -c 'CREATE DATABASE authdb;' &&
        psql -U user -tc \"SELECT 1 FROM pg_database WHERE datname = 'productdb';\" | grep -q 1 || psql -U user -c  'CREATE DATABASE productdb;' && 
        psql -U user -tc \"SELECT 1 FROM pg_database WHERE datname = 'orderdb';\" | grep -q 1 || psql -U user -c 'CREATE DATABASE orderdb;' &&
        echo 'Running schema for authdb...' &&
        psql -U user -d authdb -f /docker-entrypoint-initdb.d/init-auth.sql &&
        echo 'Running schema for productdb...' &&
        psql -U user -d productdb -f /docker-entrypoint-initdb.d/init-product.sql &&
        tail -f /dev/null
      "
